// <auto-generated />
namespace Sample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialListMigration : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205241947552_InitialListMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy8up8erVVlMs5ZQ2Xs4/qK4qPn35qP0uCwyQul1Xp6/J347D4HfR7Zn6vuUcGyv31yvcu7/s4+eF03rt6A2v1d+HXxAH72sq1Vet9ev8nN9r5h9lN4N37vbfdG+5r2DrmkwbU2T8VH6rHiXz57ny4t2/tlH51nZ5B+lX2TvzCe7ewcfpV8tC5o7eqmt1/T1i3VZZpMyt+07WLzILosLpl2n9zdZ85bI+SovhbLzYiVUHYMGv79+/ayuFq+qUikjn/7+r6t1PaWu3lS9r95k9UXehlg8vuvIvJH4APF1iH/2NYh/Zol/tmzv7UUIufr00eu2qvPP82VO3JfPXmZtm9dLvJsz6sp/j1af3o4FH97d2QML3s2Wy6plsvcQ76CJf9+TS+jXDVwif2/u9Mt6ltc3kec2M3zcNNW04IF68qW8FaJwupylw4wm4zfMScNdl20BDUGdfvbRzni82xtTFKBhTw8gM10H4Le6w/MG0udgUm1tVhCT6BifZm2Gz/J3XVUi7V/nrUcNEjJHvGCQvQGFL6uE9l6WAXVe9gYQdm8E3WvQVwNdEdw4WRZPO74Ql5vmxntfcevKdjiYCB/aGXFW5q6YGWOO7g7Yo8dfZKsVSZlnn/ST9LUYp5Pt1+9vdxYC4+40oGWXf2xPpHayi7zzLXVNmD4r6qYFh00ySOHJbNFrdgv+Mz35bNifJMNYpjV+lzc2WGhh3g4wR8ZnNLIFqU8epA7R8kr/tRT+QVZmdcR2nlTlerEcsr/87t1Or90xenpLW3ZYrUuxW9FzSGi+Hj37VpHB3UTP+GtD9Dzr0LNvUje9LVbKf18+uT0ENTk+CP3ohz+roXrpi4pRmbebPv+N28wRlGOHOH0l26fJraSEAcVEBSSxvb4XQqq1b4nQbdhsIy6k12YF+xNnDVwS647cYphdw9Gf/J796DaxrGftSMdePFbdHRiVNBbk9JS5NPkopaFfFjMo8tfXTZsvxmgwfv2LypOyIGZ3Db7IlsV53rRvqrc5AjayNV8/PLK+adPMyv83xkjLy6yezrO6HxF9Lde0N6qfm+CjwITeGGbcFORtCBoM2bYW2bs7HxQIMKrviYmVxNvPYR+vbzy6+NCAQjzs94shCADxTF5jSrOSFEzT1qRierbrJcV402KVlT6+fe16G+kC5Sy47jdP81W+BIP5Y7pNPxtsiIXZEYebBv6e8VXfDe5OVD/KGgyyROt+9tFsUtGUCgtGw5Zo/DUYfsXAxqOZn83IrBeMbYzF/AE59+RnJfrqW0nikvXSJgyJPZviwoGA3V/m04A/bJuz5Xll+LSDkWnSUUtf5G02I+Y5rtviPJu29PU0bxrOrvxkVq6pyeliks/Oll+u29W6pSHni0l57RMD7L6pfw4xQ5wff7lin/CbGAKhWdAQ8i+XT9ZFObN4P4uYwAEQkCO1OpjLFtbn4tpCelEtbwlIyffUiP+bfLGirGLefLl8nV3mw7jdTMOQYo+fFhk51gufgvKJYvI6o569LqgD/w3XH/1J7ErZ6qP/JwAA///alBmrIhcAAA=="; }
        }
    }
}
