// <auto-generated />
namespace MvcApplication22.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initalschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initalschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201302021830028_initalschema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
