// <auto-generated />
namespace SyncKanban.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class listordering : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(listordering));
        
        string IMigrationMetadata.Id
        {
            get { return "201302111748034_listordering"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
